//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SearchProjEntities : DbContext
    {
        public SearchProjEntities()
            : base("name=SearchProjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
    
        public virtual int InsertResult(string resultPath, string searchID)
        {
            var resultPathParameter = resultPath != null ?
                new ObjectParameter("resultPath", resultPath) :
                new ObjectParameter("resultPath", typeof(string));
    
            var searchIDParameter = searchID != null ?
                new ObjectParameter("SearchID", searchID) :
                new ObjectParameter("SearchID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertResult", resultPathParameter, searchIDParameter);
        }
    
        public virtual int InsertSearch(string searchPattern, string searchDirectory)
        {
            var searchPatternParameter = searchPattern != null ?
                new ObjectParameter("searchPattern", searchPattern) :
                new ObjectParameter("searchPattern", typeof(string));
    
            var searchDirectoryParameter = searchDirectory != null ?
                new ObjectParameter("SearchDirectory", searchDirectory) :
                new ObjectParameter("SearchDirectory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertSearch", searchPatternParameter, searchDirectoryParameter);
        }
    }
}
